name: Cleanup Codex task link

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  delete-codex-link:
    if: ${{ github.event.issue.pull_request && github.event.comment.user.login == 'github-actions[bot]' && contains(github.event.comment.body, 'Codex task link') }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete Codex task link comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
            });

