name: Release (standard-version)
on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump (auto | patch | minor | major)"
        required: false
        default: "auto"

jobs:
  release:
    permissions:
      contents: write   # allow pushing tags & changelog commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed so standard-version can see full history

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      # Safety: ensure repo still builds & types pass
      - run: npm run check
      - run: npm run build

      # Determine bump strategy
      - name: Run standard-version
        run: |
          if [ "${{ github.event.inputs.bump }}" = "auto" ] || [ -z "${{ github.event.inputs.bump }}" ]; then
            npm run release
          else
            npm run release -- --release-as "${{ github.event.inputs.bump }}"
          fi

      # Push changelog + tags back to the repo
      - name: Push tags and changes
        run: |
          git push --follow-tags origin HEAD:${GITHUB_REF#refs/heads/}

      # Create a GitHub Release from the tag (optional but nice)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
